name: wokwi_test
on: [push, workflow_dispatch]
jobs:
  wokwi_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Checkout tt-support-tools repo
        uses: actions/checkout@v4
        with:
          repository: TinyTapeout/tt-support-tools
          path: tt
          ref: tt08

      - name: Install iverilog
        shell: bash
        run: sudo apt-get update && sudo apt-get install -y iverilog

      # Set Python up and install cocotb
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python packages
        shell: bash
        run: pip install -r test/requirements.txt -r tt/requirements.txt

      # Fetch the truth table
      - name: Fetch Verilog and build config
        run: ./tt/tt_tool.py --create-user-config

      # Does the wokwi project have a truthtable?
      - name: Check the truthtable exists
        id: check_files
        uses: andstor/file-existence-action@v3
        with:
          files: "src/truthtable.md"

      - name: Run tests
        if: steps.check_files.outputs.files_exists == 'true'
        run: |
          cd src
          make clean
          make
          # make will return success even if the test fails, so check for failure in the results.xml
          ! grep failure results.xml

      - name: Test Summary
        uses: test-summary/action@v2.3
        with:
          paths: "src/results.xml"
        if: always()

      - name: upload vcd
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-vcd
          path: |
            src/*.vcd
            src/results.xml
